### PR TITLE
First draft of blog post on Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by embray**
for D2.3 (issue OpenDreamKit/OpenDreamKit#43)

### CODE REVIEW

**Comment by defeo** [comment]
Here's some very minor fixes

``` diff
From e8aa02134d4be1103e48a1182f220752bfd35f36 Mon Sep 17 00:00:00 2001
From: Luca De Feo <defeo@pippin>
Date: Wed, 14 Sep 2016 18:21:31 +0200
Subject: [PATCH] Typo fixes

---
 _activities/2016-09-09-emerging-technologies-wsl.md | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/_activities/2016-09-09-emerging-technologies-wsl.md b/_activities/2016-09-09-emerging-technologies-wsl.md
index 49a1791..dbb809a 100644
--- a/_activities/2016-09-09-emerging-technologies-wsl.md
+++ b/_activities/2016-09-09-emerging-technologies-wsl.md
@@ -80,9 +80,9 @@ specific features, for example, can only run on a version of the Python
 A third difficulty has to do with minor differences in user interface
 standards.  For example, a common issue in Windows support is its different
 standard for representing file paths.  While Windows paths contain a "drive
-letter" and uses the backslash ("\") to separate between folders (e.g.
-*C:\Windows\cmd.exe*), UNIX-like systems have no concept of a "drive letter",
-and use forward-slashes ("/") (e.g. */bin/bash*).  Issues like this can cause
+letter" and uses the backslash ("`\`") to separate between folders (e.g.
+`C:\Windows\cmd.exe`), UNIX-like systems have no concept of a "drive letter",
+and use forward-slashes ("`/`") (e.g. `/bin/bash`).  Issues like this can cause
 many small, but pervasive bugs when porting software between operating systems.


@@ -140,15 +140,15 @@ For example, Ubuntu's software repository already includes builds of many of
 the packages that are central to OpenDreamKit, such as
 [GAP](http://packages.ubuntu.com/trusty/gap),
 [PARI/GP](http://packages.ubuntu.com/trusty/pari-gp), and some smaller packages
-including many of the dependencies of SAGE.  SAGE itself has an unofficial
+including many of the dependencies of Sage.  Sage itself has an unofficial
 Ubuntu package--this has been found so far to nominally "work" on WSL, but
-there are have been found to be many bugs.  That said, a great deal of other
+there have been found to be many bugs.  That said, a great deal of other
 mathematical software--especially that which is less dependent on OS-specific
-features, should work already work out of the box.
+features, should already work out of the box.

 An additional potential advantage for WSL (indeed, one of the project's goals
 as detailed in [this article at Ars
-Technica](http://arstechnica.com/information-technology/2016/04/why-microsoft-needed-to-make-windows-run-linux-software/)
+Technica](http://arstechnica.com/information-technology/2016/04/why-microsoft-needed-to-make-windows-run-linux-software/))
 is to make the development tools and command-line interfaces favored by
 UNIX-oriented developers available on Windows.  This makes it possible,
 in principle, to develop software like Sage the same way on both Windows
-- 
2.9.3
```

You can push them to the PR, or you can give me the rights (new shiny GH feature) and I'll push.

I'm integrating in OpenDreamKit/OpenDreamKit#43 right now.

**Comment by defeo** [comment]
P.S.: I like it a lot

**Comment by defeo** [comment]
P.P.S.: I think html5 recommends using only one `<h1>` per page. Better double the hashes `##`.

**Comment by embray** [comment]
Thanks for the review--will update accordingly.

**Comment by embray** [comment]
@defeo It looks like neither of us are "maintainers" on this repo, so I can't give you permission to make direct edits :)

**Comment by defeo** [comment]
> It looks like neither of us are "maintainers" on this repo, so I can't give you permission to make direct edits :)

?? Any member of the "Core" team is admin on this repo. I am a member of the Core team, and I wonder why you are not. GH permissions are a mess, anyway!

**Comment by embray** [comment]
@defeo Finally got around to updating this, including your edits, and moving it from `_activities` to `_posts` as suggested previously.  Not sure what to do about the date in the filename.  Should it be updated just before merging?  Otherwise it's the date on which I actually wrote this so I'm fine either way.

**Comment by defeo** [comment]
@embray, thanks. That date in the filename goes in the metadata, which goes in the generated html and rss feed, so better change it to the date when the post is published.
And, as far as I'm concerned, that day can be today. So, if you have nothing against it, feel free to update the filename and merge the PR.

**Pull request merged**
