### PR TITLE
Blog post on Sage for Windows

### PR DESCRIPTION
**Pull request by embray**
Alright reviewed somewhat on the mailing list--ready to go as far as I'm concerned.

### CODE REVIEW

**Comment by embray** [comment]
The travis build failed but I'm not sure if it was meant to work in the first place.

**Comment by embray** [comment]
Going ahead and merging this so I can get it posted today.

**Comment by kohlhase** [comment]
wow, that is one massive blog post.

**Comment by embray** [comment]
I mean, not really--it's 7 pages printed which includes screenshots.  This is also serving as a report for the deliverable.

**Pull request merged**
