### PR TITLE
Try page demo

### PR DESCRIPTION
**Pull request by sebasguts**
Since discussed a bit in #73, I have created a stub for a try subfolder which features the following properties
* Static try page that links to binder to open a Jupyter server in which the system can be tried out
* Blog to add examples in different systems, which can either statically display the notebooks or run them on binder.

### CODE REVIEW

**Comment by nthiery** [comment]
Thanks Sebastian, this looks good! Would you have some screenshot ?

I am wondering whether we should use _post for this, or a separate collection in _try/

**Comment by nthiery** [comment]
Btw: I discussed yesterday with Min about the tension between linking to nbviewer which is fast but static and binder which may be slow but dynamic,  and the potential resolution by displaying a preview on binder while the server is being setup. He implemented a draft:

https://github.com/jupyterhub/binderhub/pull/593

**Comment by sebasguts** [comment]
The preview is a really cool thing. Do you think we should then directly link to binder, or still have the possibility to show just the static preview? I think it would be useful to default to the static preview, actually, to take load from binder.

**Comment by sebasguts** [comment]
Screenshots:
statictry
examplepage
staticpreview
staticpreviewscroll

**Comment by nthiery** [comment]
>    The preview is a really cool thing. Do you think we should then
>    directly link to binder, or still have the possibility to show just the
>    static preview? I think it would be useful to default to the static
>    preview, actually, to take load from binder.

Good question. If the page is about "Trying the software", then I'd
say that going to binder is the natural default behavior. Of course,
having a link to the static preview is a nice bonus in case binder is
out.

Thanks for the screenshots!

**Comment by sebasguts** [comment]
I updated the PR as follows:
* Rebased to new site design
* Try links and example notebooks are now managed by `.yml` files in the `_data` directory, without any posts
* Three items per row
* Example notebooks now link directly to binder

I have attached some screen shots. I would like to add some sensible examples and real links on the try page before merging, though.

image

image

**Comment by nthiery** [comment]
Hi @sebasguts,
I am back from vacations. 

That's excellent; thanks a lot. I suggest we just merge the PR as is, just without linking it from the menus. Then we empower the ODK participants by advertising opendreamkit/try and telling them how to setup the demo notebook for their respective software and/or add examples. Once the collection is non trivial, we make the page more public by linking it from the menus.

Does this sound good?

**Comment by sebasguts** [comment]
@nthiery That sounds good. I have almost finished a reasonable try page, can you give me till Saturday to finish it? It will feature links ot Sage, Singular, and GAP.

**Comment by nthiery** [comment]
>    [1]@nthiery That sounds good. I have almost finished a reasonable try
>    page, can you give me till Saturday to finish it? It will feature links
>    ot Sage, Singular, and GAP.

Perfect!

Feel free to click merge yourself when ready; I just invited you to
get direct write access.

**Comment by sebasguts** [comment]
Okay, merged it (after making the content a bit more sane). You can now advertise them using the links
> https://opendreamkit.org/try/try/ 

and

> https://opendreamkit.org/try/examples/

**Comment by nthiery** [comment]
Hmm, sounds like I am not getting all notifications these days.
Anyway: thanks @sebasguts!

**Pull request merged**
